### ISSUE TITLE
SysInternals install fails when run from Powershell DSC

### ISSUE THREAD

**Issue by chrissimon-au** [ferventcoder/chocolatey-packages#69]
Powershell DSC runs as the system user, so it attempts to setup a shortcut in the start menu of the system user, and fails as it can't save the .lnk to "C:\Windows\system32\config\systemprofile\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Process Explorer.lnk" as the path doesn't exist.

Seems related to: https://github.com/ferventcoder/chocolatey-packages/issues/61, but not sure if it will fix it.

Full error log:

	2015-05-27 22:27:29,384 [ERROR] -  Exception calling "Save" with "0" argument(s): "Unable to save shortcut "C:\Win
	2015-05-27 22:27:29,400 [ERROR] -  dows\system32\config\systemprofile\AppData\Roaming\Microsoft\Windows\Start 
	2015-05-27 22:27:29,400 [ERROR] -  Menu\Programs\Process Explorer.lnk"."
	2015-05-27 22:27:29,400 [ERROR] -  At C:\ProgramData\chocolatey\helpers\functions\Write-ChocolateyFailure.ps1:24 
	2015-05-27 22:27:29,400 [ERROR] -  char:3
	2015-05-27 22:27:29,400 [ERROR] -  +   throw "$failureMessage"
	2015-05-27 22:27:29,400 [ERROR] -  +   ~~~~~~~~~~~~~~~~~~~~~~~
	2015-05-27 22:27:29,400 [ERROR] -      + CategoryInfo          : OperationStopped: (Exception calli...Explorer.ln 
	2015-05-27 22:27:29,400 [ERROR] -     k".":String) [], RuntimeException
	2015-05-27 22:27:29,400 [ERROR] -      + FullyQualifiedErrorId : Exception calling "Save" with "0" argument(s): " 
	2015-05-27 22:27:29,400 [ERROR] -     Unable to save shortcut "C:\Windows\system32\config\systemprofile\AppData\  
	2015-05-27 22:27:29,400 [ERROR] -    Roaming\Microsoft\Windows\Start Menu\Programs\Process Explorer.lnk"."
	2015-05-27 22:27:29,431 [ERROR] - The install of sysinternals was NOT successful.

I've worked around for now with a DSC File dependency to create the path first but it's a bit of a hack.

		File SysInternalsPath
		{
			Ensure = "Present"
			Type = "Directory"
			DestinationPath = "%systemroot%\System32\config\systemprofile\AppData\Roaming\Microsoft\Windows\Start Menu\Programs"
		}
		
		cChocoPackageInstaller installSysInternals
		{
			Name = "sysinternals"
			DependsOn = @("[cChocoInstaller]installChoco","[File]SysInternalsPath")
		}

Would be nicer if it handled the exception and didn't treat failure to add the shortcut as failure to install the package - or added to the start menu for all users, so admin users still have it even if installed via DSC.

**Comment by ferventcoder** [comment]
This was fixed in choco 0.9.9.6 - can you verify?

**Comment by ferventcoder** [comment]
This is the relevant issue - https://github.com/chocolatey/choco/issues/264

**Comment by ferventcoder** [comment]
Once you've verified this has been fixed, please close this issue.

**Comment by chrissimon-au** [comment]
Unfortunately still happening for me with choco 0.9.9.6 - full log:

	2015-05-28 20:17:35,217 [INFO ] - ============================================================
	2015-05-28 20:17:35,248 [INFO ] - Chocolatey v0.9.9.6
	2015-05-28 20:17:35,326 [INFO ] - Installing the following packages:
	2015-05-28 20:17:35,326 [INFO ] - sysinternals
	2015-05-28 20:17:35,326 [INFO ] - By installing you accept licenses for the packages.
	2015-05-28 20:17:39,498 [INFO ] - 
	sysinternals v2015.05.26
	2015-05-28 20:17:40,607 [INFO ] -  Get-BinRoot is going to be deprecated by v1. Many packages no longer require it since the folders no longer have versions on them.
	2015-05-28 20:17:42,982 [INFO ] -  Extracting C:\Windows\TEMP\chocolatey\sysinternals\sysinternalsInstall.zip to C:\tools\sysinternals...
	2015-05-28 20:17:44,216 [INFO ] -  C:\tools\sysinternals
	2015-05-28 20:17:44,529 [WARN ] -  WARNING: Write-ChocolateyFailure is deprecated. If you are the package 
	2015-05-28 20:17:44,545 [INFO ] -  maintainer, please use 'throw $_.Exception' instead.
	2015-05-28 20:17:44,638 [ERROR] -  Exception calling "Save" with "0" argument(s): "Unable to save shortcut "C:\Win
	2015-05-28 20:17:44,638 [ERROR] -  dows\system32\config\systemprofile\AppData\Roaming\Microsoft\Windows\Start 
	2015-05-28 20:17:44,638 [ERROR] -  Menu\Programs\Process Explorer.lnk"."
	2015-05-28 20:17:44,654 [ERROR] -  At C:\ProgramData\chocolatey\helpers\functions\Write-ChocolateyFailure.ps1:24 
	2015-05-28 20:17:44,654 [ERROR] -  char:3
	2015-05-28 20:17:44,654 [ERROR] -  +   throw "$failureMessage"
	2015-05-28 20:17:44,654 [ERROR] -  +   ~~~~~~~~~~~~~~~~~~~~~~~
	2015-05-28 20:17:44,654 [ERROR] -      + CategoryInfo          : OperationStopped: (Exception calli...Explorer.ln 
	2015-05-28 20:17:44,654 [ERROR] -     k".":String) [], RuntimeException
	2015-05-28 20:17:44,654 [ERROR] -      + FullyQualifiedErrorId : Exception calling "Save" with "0" argument(s): " 
	2015-05-28 20:17:44,654 [ERROR] -     Unable to save shortcut "C:\Windows\system32\config\systemprofile\AppData\  
	2015-05-28 20:17:44,654 [ERROR] -    Roaming\Microsoft\Windows\Start Menu\Programs\Process Explorer.lnk"."
	2015-05-28 20:17:44,717 [ERROR] - The install of sysinternals was NOT successful.
	2015-05-28 20:17:44,717 [ERROR] - Error while running 'C:\ProgramData\chocolatey\lib\sysinternals\tools\chocolateyInstall.ps1'.
	 See log for details.
	2015-05-28 20:17:46,732 [WARN ] - 
	Chocolatey installed 0/1 package(s). 1 package(s) failed.
	 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
	2015-05-28 20:17:46,732 [ERROR] - Failures:
	2015-05-28 20:17:46,732 [ERROR] -  - sysinternals

**Comment by ferventcoder** [comment]
Wait, this might be in the package itself... looking.

**Comment by ferventcoder** [comment]
Yep, it's in the package -  https://github.com/ferventcoder/chocolatey-packages/blob/master/automatic/sysinternals/tools/chocolateyInstall.ps1#L33-L40

The helper in choco would work correctly, if this package were using it. Ugh

**Comment by ferventcoder** [comment]
@chrissimon-au by the way, for full logs, we like both debug and verbose output - so add `-dv` to the args. We don't need it for this package as we have some things to fix. Thanks!

**Comment by chrissimon-au** [comment]
No problems - will remember for the future - thanks!

**Comment by ferventcoder** [comment]
This should now be fixed completely in the new version.

**Comment by ferventcoder** [comment]
Let me know if it is now.
